export const countryLogos: Record<string, string> = {
  "United States": "/flags/us.svg",
  Canada: "/flags/ca.svg",
  Switzerland: "/flags/ch.svg",
  Australia: "/flags/au.svg",
  "Hong Kong": "/flags/hk.svg",
  Lithuania: "/flags/lt.svg",
};

export const licenses: License[] = [
  // United States
  { country: "United States", region: "Federal", authority: "U.S. Financial Crimes Enforcement Network", type: "Money Service Business Registration", ref: "31000201469839", company: "PipsTrust Financial LLC", url: "https://www.fincen.gov", flag: "https://cdn.maryland.gov/mdwds/0.47.2/img/md_wordmark_horizontal.svg" },
  { country: "United States", region: "Alabama", authority: "State Banking Department", type: "Consumer Credit License", ref: "MC 22385", company: "PipsTrust Financial LLC", url: "https://www.banking.alabama.gov", flag: "🇺🇸" },
  { country: "United States", region: "Alabama", authority: "Alabama Securities Commission", type: "Money Transmitter License", ref: "# 769", company: "PipsTrust Financial LLC", url: "https://www.asc.alabama.gov", flag: "🇺🇸" },
  { country: "United States", region: "Arizona", authority: "Department of Insurance and Financial Institutions", type: "Money Transmitter License", ref: "MT-1034818", company: "PipsTrust Financial LLC", url: "https://difi.az.gov", flag: "🇺🇸" },
  { country: "United States", region: "Arizona", authority: "Department of Insurance and Financial Institutions", type: "Consumer Lender License", ref: "CL-1017838", company: "PipsTrust Financial LLC", url: "https://difi.az.gov", flag: "🇺🇸" },
  { country: "United States", region: "Arkansas", authority: "Arkansas Securities Department", type: "Money Transmitter License", ref: "125678", company: "PipsTrust Financial LLC", url: "http://securities.arkansas.gov", flag: "🇺🇸" },
  { country: "United States", region: "California", authority: "Department of Financial Protection and Innovation", type: "Financing Law License", ref: "60DBQ-119812", company: "PipsTrust Financial LLC", url: "https://dfpi.ca.gov", flag: "🇺🇸" },
  { country: "United States", region: "District of Columbia", authority: "Department of Insurance, Securities and Banking", type: "Money Lender License", ref: "ML 1898544", company: "PipsTrust Financial LLC", url: "https://disb.dc.gov", flag: "🇺🇸" },
  { country: "United States", region: "Delaware", authority: "Office of the State Bank Commissioner", type: "Lender License", ref: "035538", company: "PipsTrust Financial LLC", url: "https://banking.delaware.gov", flag: "🇺🇸" },
  { country: "United States", region: "Georgia", authority: "Department of Banking and Finance", type: "Seller of Payment Instruments License", ref: "1799753", company: "PipsTrust Financial LLC", url: "https://dbf.georgia.gov", flag: "🇺🇸" },
  { country: "United States", region: "Idaho", authority: "Department of Finance", type: "Regulated Lender License", ref: "RRL-11385", company: "PipsTrust Financial LLC", url: "https://www.finance.idaho.gov", flag: "🇺🇸" },
  { country: "United States", region: "Illinois", authority: "Department of Financial and Professional Regulation", type: "Consumer Installment Loan License", ref: "CI.0014461-H", company: "PipsTrust Financial LLC", url: "https://idfpr.com", flag: "🇺🇸" },
  { country: "United States", region: "Iowa", authority: "Iowa Division of Banking", type: "Money Service License", ref: "2022-0009", company: "PipsTrust Financial LLC", url: "http://www.idob.state.ia.us", flag: "🇺🇸" },
  { country: "United States", region: "Kansas", authority: "Office of the State Bank Commissioner", type: "Supervised Loan License", ref: "SL.0026405", company: "PipsTrust Financial LLC", url: "https://osbckansas.org", flag: "🇺🇸" },
  { country: "United States", region: "Maryland", authority: "Commissioner of Financial Regulation", type: "Installment Loan License", ref: "03-1898745", company: "PipsTrust Financial LLC", url: "https://www.maryland.gov/", flag: "🇺🇸" },
  { country: "United States", region: "Maryland", authority: "Commissioner of Financial Regulation", type: "Money Transmitter License", ref: "1898755", company: "PipsTrust Financial LLC", url: "https://www.maryland.gov", flag: "🇺🇸" },
  { country: "United States", region: "Minnesota", authority: "Department of Commerce", type: "Regulated Loan Company License", ref: "MN-RL-1996754", company: "PipsTrust Financial LLC", url: "https://mn.gov/commerce", flag: "🇺🇸" },
  { country: "United States", region: "Minnesota", authority: "Department of Commerce", type: "Money Transmitter License", ref: "MN-MT-1848786", company: "PipsTrust Financial LLC", url: "https://mn.gov/commerce", flag: "🇺🇸" },
  { country: "United States", region: "Mississippi", authority: "Department of Banking and Consumer Finance", type: "Money Transmitter License", ref: "1898643", company: "PipsTrust Financial LLC", url: "https://dbcf.ms.gov", flag: "🇺🇸" },
  { country: "United States", region: "Missouri", authority: "Division of Finance", type: "Sale of Checks & Money Transmitter License", ref: "MO-23-8913", company: "PipsTrust Financial LLC", url: "https://finance.mo.gov", flag: "🇺🇸" },
  { country: "United States", region: "Montana", authority: "Division of Banking and Financial Institutions", type: "Consumer Loan License", ref: "1877754", company: "PipsTrust Financial LLC", url: "https://banking.mt.gov", flag: "🇺🇸" },
  { country: "United States", region: "New Hampshire", authority: "Banking Department", type: "Small Loan Lender License", ref: "23521-SM", company: "PipsTrust Financial LLC", url: "https://www.nh.gov/banking", flag: "🇺🇸" },
  { country: "United States", region: "New Hampshire", authority: "Banking Department", type: "Money Transmitter License", ref: "24189-MT", company: "PipsTrust Financial LLC", url: "https://www.nh.gov/banking", flag: "🇺🇸" },
  { country: "United States", region: "North Dakota", authority: "Department of Financial Institutions", type: "Money Broker License", ref: "MB104829", company: "PipsTrust Financial LLC", url: "https://www.nd.gov/dfi", flag: "🇺🇸" },
  { country: "United States", region: "North Dakota", authority: "Department of Financial Institutions", type: "Money Transmitter License", ref: "MT104944", company: "PipsTrust Financial LLC", url: "https://www.nd.gov/dfi", flag: "🇺🇸" },
  { country: "United States", region: "Oregon", authority: "Division of Financial Regulation", type: "Consumer Finance License", ref: "1998556", company: "PipsTrust Financial LLC", url: "https://dfr.oregon.gov", flag: "🇺🇸" },
  { country: "United States", region: "Oregon", authority: "Division of Financial Regulation", type: "Money Transmitter License", ref: "1878845", company: "PipsTrust Financial LLC", url: "https://dfr.oregon.gov", flag: "🇺🇸" },
  { country: "United States", region: "Pennsylvania", authority: "Department of Banking and Securities", type: "Money Transmitter License", ref: "94060", company: "PipsTrust Financial LLC", url: "https://dobs.pa.gov", flag: "🇺🇸" },
  { country: "United States", region: "South Dakota", authority: "Division of Banking", type: "Money Transmitter License", ref: "1878745.MT", company: "PipsTrust Financial LLC", url: "https://dlr.sd.gov/banking", flag: "🇺🇸" },
  { country: "United States", region: "Utah", authority: "Department of Financial Institutions", type: "Consumer Credit Notification", ref: "—", company: "PipsTrust Financial LLC", url: "https://dfi.utah.gov", flag: "🇺🇸" },
  { country: "United States", region: "West Virginia", authority: "West Virginia Division of Financial Institutions", type: "Money Transmitter License", ref: "WVMT-1899654", company: "PipsTrust Financial LLC", url: "https://dfi.wv.gov", flag: "🇺🇸" },
  { country: "United States", region: "Wyoming", authority: "Department of Audit", type: "Consumer Lender License", ref: "CL-4229", company: "PipsTrust Financial LLC", url: "https://audit.wyo.gov", flag: "🇺🇸" },
  // International
  { country: "Canada", region: "", authority: "Financial Transactions and Reports Analysis Centre of Canada", type: "Money Service Business Registration", ref: "M20280268", company: "PipsTrust Capital Inc.", url: "https://www.fintrac-canafe.gc.ca", flag: "🇨🇦" },
  { country: "Canada", region: "", authority: "Financial Transactions and Reports Analysis Centre of Canada", type: "Money Service Business Registration", ref: "M21199887", company: "PipsTrust Financial Services Inc.", url: "https://www.fintrac-canafe.gc.ca", flag: "🇨🇦" },
  { country: "Switzerland", region: "", authority: "SO-FIT", type: "Affiliated Member — Self-Regulatory Organization", ref: "—", company: "PipsTrust AG", url: "https://so-fit.ch", flag: "🇨🇭" },
  { country: "Australia", region: "", authority: "Australian Securities and Investment Commission", type: "Registration as Foreign Company", ref: "647054530", company: "PipsTrust Capital Inc.", url: "https://asic.gov.au", flag: "🇦🇺" },
  { country: "Hong Kong", region: "", authority: "Companies Registry", type: "Trust or Company Service Provider License", ref: "TC017446", company: "PipsTrust Finance Limited", url: "https://www.cr.gov.hk", flag: "🇭🇰" },
  { country: "Lithuania", region: "", authority: "Financial Crime Investigation Service", type: "Virtual Currency Exchange & Depository Wallet Operator", ref: "—", company: "PipsTrust Services UAB", url: "#", flag: "🇱🇹" },
];